# Build the Docker image on master branch

name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-push:
    name: deploy the docker image to docker hub and k8s
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Set the RELEASE_VERSION environment variable with the first seven characteres of the last commit sha value
    - name: Get release version
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_SHA} | cut -c 1-7)

    # Display the RELEASE_VERSION environment variable
    - name: Display release version
      run: echo ${{ env.RELEASE_VERSION }}

    # Build and push a docker image tagged with the current commit sha value as a release version
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: danvergara/freedom-analysis
        tags: "latest,${{ env.RELEASE_VERSION }}"

    # Deploy the current container image to my k8s cluster
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
      with:
        args: set image --record deployment/freedom-analysis freedom-analysis=danvergara/freedom-analysis:${{ env.RELEASE_VERSION }}
